config/routes.rb
Finance::Application.routes.draw do

  devise_for :users

  root :to => 'portfolio#show'

  resource :portfolio, only: [:show], controller: 'Portfolio' do
    resources :stocks, except: [:index, :show]
  end

end

app/models/market_price.rb
class MarketPrice < ActiveRecord::Base

  validates :symbol, presence: true, uniqueness: true

  STALE_THRESHOLD = 10.minutes

  after_create :queue_update!

  def self.get(symbol)
    if mp = find_by_symbol(symbol)
      mp.queue_update! if mp.stale?
    else
      mp = create!(symbol: symbol)
    end
    mp.price
  end

  def stale?
    price.nil? or updated_at < STALE_THRESHOLD.ago
  end

  def queue_update!
    job = UpdateMarketPriceFromGoogle.new(symbol)
    Delayed::Job.enqueue(job)
  end

end

app/models/portfolio.rb
class Portfolio < SimpleDelegator

  [:original_value, :current_value, :roi].each do |attribute|
    define_method(attribute) { sum_on(attribute) }
  end


  private

  def sum_on(attribute)
    stocks = __getobj__
    stocks.any? ? stocks.map(&attribute).reduce(:+) : 0
  rescue TypeError, NoMethodError
    # the values might be nil
    nil
  end
end

app/models/stock.rb
class Stock < ActiveRecord::Base

  belongs_to :user

  attr_accessible :symbol, :shares, :price

  validates :symbol, presence: true

  [:shares, :price].each do |numeric|
    validates numeric, presence: true, format: /\A\d+(\.\d*)?\z/
  end

  def original_value
    shares * price
  end

  def roi
    current_value - original_value rescue nil
  end

  def current_value
    shares * current_price rescue nil
  end

  def current_price
    MarketPrice.get(symbol)
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me

  validates :email, presence: true, uniqueness: true

  has_many :stocks

  def portfolio
    Portfolio.new(stocks)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

  before_filter :authenticate_user!

end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController

  def show
    @portfolio = current_user.portfolio
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def new
    @stock = current_user.stocks.build

    respond_to do |format|
      format.html
      format.json { render json: @stock }
    end
  end

  def edit
    @stock = current_user.stocks.find(params[:id])
  end

  def create
    @stock = current_user.stocks.new(params[:stock])

    respond_to do |format|
      if @stock.save
        format.html { redirect_to portfolio_url, notice: "#{@stock.symbol} was added." }
        format.json { render json: @stock, status: :created, location: @stock }
      else
        format.html { render action: "new" }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @stock = current_user.stocks.find(params[:id])

    respond_to do |format|
      if @stock.update_attributes(params[:stock])
        format.html { redirect_to portfolio_url, notice: 'Stock was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @stock = current_user.stocks.find(params[:id])
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to portfolio_url, notice: "#{@stock.symbol} was removed." }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def currency(amount)
    if amount
      css_class = 'currency'
      css_class << ' negative' if amount < 0
      content_tag(:span, number_to_currency(amount.abs), :class => css_class)
    else
      '<span class="updating">Updating...</span>'.html_safe
    end
  end
end

app/views/layouts/_flashes.html.haml
- flash.each do |key, msg|
  %div.alert{:id => key}
    %p= msg

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title= content_for?(:title) ? yield(:title) : "Finance"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    / Le styles
    :css
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    = stylesheet_link_tag "application", :media => "all"
    / Le fav and touch icons
    %link{:href => "images/favicon.ico", :rel => "shortcut icon"}/
    %link{:href => "images/apple-touch-icon.png", :rel => "apple-touch-icon"}/
    %link{:href => "images/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
    %link{:href => "images/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "/"}Finance
          .container-fluid.nav-collapse
            %ul.nav
              %li= link_to "Link 1", "#"
              %li= link_to "Link 2", "#"
              - if user_signed_in?
                %li.dropdown
                  %a.dropdown-toggle{'data-toggle' => 'dropdown', 'href' => '#'}
                    = current_user.email
                    %b.caret
                  %ul.dropdown-menu
                    %li= link_to 'Sign Out', destroy_user_session_path, :method => :delete

    .container-fluid

      .row-fluid
        .span3
          .well.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "#"
              %li= link_to "Link 2", "#"
              %li= link_to "Link 3", "#"
        .span9
          = render 'layouts/flashes'
          = yield

      %footer
        %p &copy; Company 2012
    /
      Le javascript
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/portfolio/show.html.haml
%h1 My Portfolio

%table.table.table-striped.table-bordered
  %tr
    %th Original Value
    %td#portfolio_original_value= currency(@portfolio.original_value)
  %tr.currency_value
    %th Current Value
    %td#portfolio_current_value= currency(@portfolio.current_value)
  %tr.roi
    %th ROI
    %td#portfolio_roi= currency(@portfolio.roi)

%table.table.table-striped.table-bordered
  %thead
    %tr
      %th Ticker Symbol
      %th Shares
      %th Price Paid
      %th Market Price
      %th ROI
      %th Actions
  - @portfolio.each do |stock|
    = content_tag_for(:tr, stock) do
      %td= stock.symbol
      %td= stock.shares
      %td= currency(stock.price)
      %td= currency(stock.current_price)
      %td= currency(stock.roi)
      %td
        = link_to 'Edit', edit_portfolio_stock_path(stock), :class => 'btn'
        = link_to 'Remove', [:portfolio, stock], :method => :delete, :class => 'btn btn-danger'

= link_to 'Add a Stock', new_portfolio_stock_path, :class => 'btn btn-success'

app/views/stocks/_form.html.haml
= simple_form_for([:portfolio, @stock]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :symbol
    = f.input :shares
    = f.input :price

  .form-actions
    = f.button :submit, "Add to My Portfolio"

app/views/stocks/edit.html.haml
%h1 Editing stock

= render 'form'

= link_to 'Back', portfolio_path

app/views/stocks/new.html.haml
%h1 New stock

= render 'form'

= link_to 'Back', portfolio_path